(() => {
const canvas=document.querySelector('.globe-canvas');if(!canvas)return;const ctx=canvas.getContext('2d'),dpr=Math.min(devicePixelRatio||1,2),texture=new Image(),sphere=document.createElement('canvas'),sctx=sphere.getContext('2d');texture.src='assets/earth-blue-marble.png';let tex=null,tw=0,th=0,width=0,height=0,radius=0,centerLon=120,centerLat=12,dragging=false,lastX=0,lastY=0,lastTime=performance.now();
const locations=[{lon:121,lat:24,label:'TAIWAN',value:'RISK 24.6'},{lon:140,lat:36,label:'TOKYO',value:'NIKKEI FUT'},{lon:-74,lat:41,label:'NEW YORK',value:'S&P 500'},{lon:0,lat:52,label:'LONDON',value:'FTSE FUT'},{lon:104,lat:1,label:'SINGAPORE',value:'SGX'},{lon:12,lat:49,label:'EUROPE',value:'EUA €71.48'}],rad=v=>v*Math.PI/180;
const project=(lon,lat)=>{const l=rad(lon-centerLon),p=rad(lat),p0=rad(centerLat),cp=Math.cos(p),sp=Math.sin(p),visible=Math.sin(p0)*sp+Math.cos(p0)*cp*Math.cos(l);return{x:width/2+radius*cp*Math.sin(l),y:height/2-radius*(Math.cos(p0)*sp-Math.sin(p0)*cp*Math.cos(l)),visible}};
const resize=()=>{const r=canvas.getBoundingClientRect();width=r.width;height=r.height;radius=Math.min(width,height)*.455;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)};
texture.addEventListener('load',()=>{const source=document.createElement('canvas');source.width=texture.naturalWidth;source.height=texture.naturalHeight;const sc=source.getContext('2d',{willReadFrequently:true});sc.drawImage(texture,0,0);tw=source.width;th=source.height;tex=sc.getImageData(0,0,tw,th).data});
const curve=points=>{let drawing=false;ctx.beginPath();points.forEach(([lon,lat])=>{const p=project(lon,lat);if(p.visible>0){drawing?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);drawing=true}else drawing=false});ctx.stroke()};
const satelliteEarth=(cx,cy)=>{if(!tex)return false;const size=Math.max(180,Math.min(430,Math.round(radius*1.42)));if(sphere.width!==size){sphere.width=size;sphere.height=size}const frame=sctx.createImageData(size,size),pixels=frame.data,p0=rad(centerLat),c0=Math.cos(p0),s0=Math.sin(p0);for(let y=0;y<size;y++){const ny=1-(y+.5)/size*2;for(let x=0;x<size;x++){const nx=(x+.5)/size*2-1,rr=nx*nx+ny*ny;if(rr>1)continue;const nz=Math.sqrt(1-rr),phi=Math.asin(Math.max(-1,Math.min(1,ny*c0+nz*s0))),lambda=Math.atan2(nx,nz*c0-ny*s0);let lon=centerLon+lambda*180/Math.PI;lon=((lon+180)%360+360)%360-180;const tx=Math.min(tw-1,Math.max(0,Math.floor((lon+180)/360*tw))),ty=Math.min(th-1,Math.max(0,Math.floor((90-phi*180/Math.PI)/180*th))),si=(ty*tw+tx)*4,di=(y*size+x)*4,light=Math.max(.16,Math.min(1.08,.28+nz*.8-nx*.24-ny*.07)),air=Math.pow(1-nz,3)*.48;pixels[di]=Math.min(255,tex[si]*light+48*air);pixels[di+1]=Math.min(255,tex[si+1]*light+128*air);pixels[di+2]=Math.min(255,tex[si+2]*light+235*air);pixels[di+3]=255}}sctx.putImageData(frame,0,0);ctx.drawImage(sphere,cx-radius,cy-radius,radius*2,radius*2);return true};
const draw=now=>{if(!dragging)centerLon=(centerLon+Math.min((now-lastTime)*.006,.35)+540)%360-180;lastTime=now;ctx.clearRect(0,0,width,height);const cx=width/2,cy=height/2,halo=ctx.createRadialGradient(cx,cy,radius*.78,cx,cy,radius*1.12);halo.addColorStop(0,'rgba(53,142,255,0)');halo.addColorStop(.78,'rgba(53,142,255,0)');halo.addColorStop(.91,'rgba(85,177,255,.3)');halo.addColorStop(1,'rgba(85,177,255,0)');ctx.beginPath();ctx.arc(cx,cy,radius*1.12,0,Math.PI*2);ctx.fillStyle=halo;ctx.fill();if(!satelliteEarth(cx,cy)){const ocean=ctx.createRadialGradient(cx-radius*.38,cy-radius*.42,radius*.06,cx,cy,radius);ocean.addColorStop(0,'#4fa7d7');ocean.addColorStop(.62,'#123a59');ocean.addColorStop(1,'#020b14');ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.fillStyle=ocean;ctx.fill()}ctx.save();ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.clip();ctx.strokeStyle='rgba(177,226,255,.10)';ctx.lineWidth=.7;for(let lat=-75;lat<=75;lat+=15){const pts=[];for(let lon=-180;lon<=180;lon+=3)pts.push([lon,lat]);curve(pts)}for(let lon=-180;lon<180;lon+=15){const pts=[];for(let lat=-88;lat<=88;lat+=3)pts.push([lon,lat]);curve(pts)}locations.forEach(l=>{const p=project(l.lon,l.lat);if(p.visible<.12)return;ctx.globalAlpha=Math.min(1,(p.visible-.1)*2.2);ctx.beginPath();ctx.arc(p.x,p.y,3.5,0,Math.PI*2);ctx.fillStyle='#d7ff63';ctx.fill();ctx.beginPath();ctx.arc(p.x,p.y,10,0,Math.PI*2);ctx.strokeStyle='rgba(215,255,99,.5)';ctx.stroke();ctx.font='600 9px DM Mono, monospace';ctx.fillStyle='#efffd1';ctx.fillText(l.label,p.x+13,p.y-3);ctx.font='8px DM Mono, monospace';ctx.fillStyle='#baff39';ctx.fillText(l.value,p.x+13,p.y+9);ctx.globalAlpha=1});const shade=ctx.createLinearGradient(cx-radius,cy,cx+radius,cy);shade.addColorStop(0,'rgba(164,219,255,.05)');shade.addColorStop(.45,'rgba(0,0,0,0)');shade.addColorStop(1,'rgba(0,3,10,.72)');ctx.fillStyle=shade;ctx.fillRect(cx-radius,cy-radius,radius*2,radius*2);ctx.restore();ctx.beginPath();ctx.arc(cx,cy,radius+.8,0,Math.PI*2);ctx.strokeStyle='rgba(105,190,255,.72)';ctx.lineWidth=2.2;ctx.stroke();requestAnimationFrame(draw)};
canvas.addEventListener('pointerdown',e=>{e.stopPropagation();dragging=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{e.stopPropagation();if(!dragging)return;centerLon-=(e.clientX-lastX)*.42;centerLat=Math.max(-55,Math.min(55,centerLat+(e.clientY-lastY)*.28));lastX=e.clientX;lastY=e.clientY});const stop=e=>{e.stopPropagation();dragging=false};canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop);new ResizeObserver(resize).observe(canvas);resize();requestAnimationFrame(draw);
})();
