const NEWS_DATA={
  'etf-2025':{date:'2025.10.17',tag:'MARKETS · TAIWAN',title:'AI 氣候金融避險系統亮相 2025 臺灣週 ETF 投資博覽會',dek:'從氣候資料到投資決策，中山永續金融科技在臺灣週現場展示如何讓氣候風險成為可執行的避險策略。',lead:'2025 臺灣週 ETF 投資博覽會匯集市場、產品與投資教育資源。我們帶著 AI 氣候金融避險系統走進展會，向投資人與產業夥伴展示：氣候風險不只是一項永續議題，也可以成為投資組合管理的一部分。',sections:[{heading:'把風險轉譯為市場訊號',text:'系統整合全球氣候資料、產業暴露與金融市場資訊，透過 AI 科學計算形成氣候衝擊分數、資產韌性分數及避險配置建議。投資人可以從個股、ETF 與期貨的視角，理解極端氣候可能如何影響供應鏈、營運與價格波動。',image:'assets/news/etf-01.jpg',caption:'中山永續金融科技團隊於 2025 臺灣週 ETF 投資博覽會展示 AI 氣候金融避險系統。'},{heading:'讓永續投資更具可解釋性',text:'我們以視覺化量化介面呈現動能、波動、氣候風險與 ESG 韌性，並透過不同情境模擬檢視投資組合的避險效率。這使永續投資不只停留在評分，也能連結到具體的資產配置與風險管理。',image:'assets/news/etf-02.jpg',caption:'現場交流聚焦於氣候因子、ETF 投資與期貨避險的整合應用。'}],links:[['台灣證券交易所｜臺灣週相關新聞','https://accessibility.twse.com.tw/zh/about/news/news/content.html?8a8216d697fc438f0198a16d2a9702af'],['工商時報｜2025 臺灣週 ETF 投資博覽會','https://www.ctee.com.tw/news/20251020700668-430301'],['高雄市政府經濟發展局｜活動消息','https://invest.kcg.gov.tw/News_Content.aspx?n=8CE973AC5F6EE514&sms=D7173346CB507235&s=29243D13907957CC']]},
  'forum-2025':{date:'2025.10.21',tag:'FORUM · FINTECH',title:'2025 永續金融科技創新投資國際論壇',dek:'跨域對話匯聚永續金融、人工智慧與投資實務，探索氣候科技如何進入金融決策核心。',lead:'中山永續金融科技參與 2025 永續金融科技創新投資國際論壇，與產官學界夥伴交流 AI、氣候風險與金融創新的落地路徑。',sections:[{heading:'從資料到資本市場應用',text:'我們分享如何以氣候衝擊因子連結企業、資產與投資組合，並透過量化模型支持情境分析與避險決策。',image:'assets/news/forum-01.jpg',caption:'論壇現場聚焦永續金融科技的國際趨勢與應用。'},{heading:'建立跨域合作網絡',text:'永續金融需要氣候科學、金融工程與產業知識共同參與。本次論壇讓不同領域的專業者建立具體連結。',image:'assets/news/forum-02.jpg',caption:'中山永續金融科技與論壇夥伴交流創新投資方法。'}],links:[['工商時報｜永續金融科技創新投資國際論壇','https://www.ctee.com.tw/news/20251023700901-431201']]},
  'smart-city-2026':{date:'2026.03.20',tag:'EXPO · KAOHSIUNG',title:'2026 高雄智慧城市展',dek:'以城市氣候資料與金融模型連結韌性治理，展示 AI 在智慧城市與永續金融中的新角色。',lead:'在 2026 高雄智慧城市展，中山永續金融科技展示全球氣候資料庫與 AI 風險量化能力，讓城市、企業與金融機構能以共同的資料語言理解氣候衝擊。',sections:[{heading:'看見城市尺度的氣候衝擊',text:'平台以世界地圖呈現颱風、洪水、地震、乾旱等事件，並將位置、產業與資產曝險串接至金融風險分析。',image:'assets/news/smart-city.jpg',caption:'2026 高雄智慧城市展現場，展示氣候資料的城市與金融應用。'}],links:[['高雄智慧城市｜官方活動新聞','https://smartcity.kcg.gov.tw/News_Content.aspx?n=F77C2541065E3DAD&sms=D6ED426045071971&s=C1D5E1631E0637A5']]},
  'learning-circle-2026':{date:'2026.03.13',tag:'PROGRAM · LEARNING',title:'2026 永續金融科技創新投資學習圈',dek:'以專題演講、工作坊與跨域交流，建立永續 × 金融 × 科技的共同學習場域。',lead:'中山永續金融科技參與創新投資學習圈，將 AI 氣候風險量化的實務經驗帶入交流，與青年、研究者及創業團隊共同討論未來投資工具。',sections:[{heading:'把模型變成可以討論的工具',text:'學習圈以案例拆解氣候風險指標、投資組合與避險工具，讓參與者從資料理解走向策略設計。',image:'assets/news/forum-02.jpg',caption:'以跨領域交流推進永續金融科技的實務學習。'}],links:[['國立中山大學創業育成中心｜學習圈活動','https://www.facebook.com/nsysustartup/posts/1455724693009496/']]},
  'awe-2026':{date:'2026.05.11',tag:'GLOBAL · ENTREPRENEURSHIP',title:'2026 女性創業飛雁計畫',dek:'連結國際創業資源與永續金融科技，持續拓展具影響力的創新網絡。',lead:'中山永續金融科技參與女性創業培力與國際交流，分享從氣候資料、AI 模型到金融應用的創業實踐。',sections:[{heading:'讓科技創業回應全球挑戰',text:'氣候風險、金融韌性與數位工具的交會，提供女性創業者與跨域團隊創造新服務的機會。',image:'assets/news/awe.jpg',caption:'女性創業飛雁計畫促進國際交流、創業能力與市場連結。'}],links:[['AIT｜Academy for Women Entrepreneurs','https://www.ait.org.tw/zhtw/fact-sheet-the-academy-for-women-entrepreneurs-zh/']]},
  'meet-south-2026':{date:'2026.08.28',tag:'STARTUP · SOUTH',title:'2026 亞灣新創大南方',dek:'在南台灣創新聚落展示 AI 氣候金融科技，連結產業、資本與城市場域。',lead:'中山永續金融科技於亞灣新創大南方分享 AI 氣候金融避險系統，與企業及創業生態夥伴交流氣候數據的商業應用。',sections:[{heading:'從高雄走向全球市場',text:'以高雄為研發與應用基地，我們持續將全球氣候資料、金融模型與產業需求結合，打造可擴展的永續金融科技服務。',image:'assets/news/meet-south.jpg',caption:'亞灣新創大南方匯聚南台灣創業與產業創新能量。'}],links:[['高雄市政府青年局｜亞灣新創大南方','https://youth.kcg.gov.tw/News_Content.aspx?n=9&s=13705&sms=10146']]},
  'finnovation-2025':{date:'2025.01.15',tag:'MILESTONE · KAOHSIUNG',title:'進駐高雄金融科技創新園區',dek:'以高雄作為 AI 氣候金融科技的研發基地，開啟產品驗證與跨域合作的新階段。',lead:'中山永續金融科技正式進駐高雄金融科技創新園區，持續推進氣候資料、金融模型與 AI 投資決策系統的研發。',sections:[{heading:'打造氣候金融科技的研發節點',text:'園區提供金融、科技與創業資源的連結，使我們能更快速與金融機構、企業及研究夥伴展開驗證與合作。',image:'assets/news/finnovation-01.jpg',caption:'中山永續金融科技進駐高雄金融科技創新園區。'},{heading:'從原型走向應用',text:'團隊將持續優化氣候衝擊因子、投資量化介面與永續金融資料庫，讓風險資訊可以進入實際決策流程。',image:'assets/news/finnovation-02.jpg',caption:'以園區為基地，串連金融科技創新生態。'}],links:[['工商時報｜高雄金融科技創新園區相關新聞','https://www.ctee.com.tw/news/20250115701305-430503']]}
};
